name: Lane Consulting
favicon: null
layout_spectrum: 0.13681907998397946
typography_spectrum: 0.005655321525409818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2029798566363752
  lightness: 0.9164727272000164
  saturation: 0.49599702353589237
  rhythmicContrast: 0.4248600045684725
purpose: []
